class GroceryList {
  static List<Map<String, dynamic>> groceryItems = [
    {
      "id": 1,
      "product_name": "Aashirvaad Whole Wheat Atta",
      "category": "Staples",
      "price": 272.00,
      "currency": "INR",
      "quantity": 5,
      "unit": "kg",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 2,
      "product_name": "Amul Pasteurized Butter",
      "category": "Dairy",
      "price": 240.00,
      "currency": "INR",
      "quantity": 500,
      "unit": "g",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 3,
      "product_name": "Tata Salt",
      "category": "Staples",
      "price": 28.00,
      "currency": "INR",
      "quantity": 1,
      "unit": "kg",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 4,
      "product_name": "India Gate Basmati Rice (Classic)",
      "category": "Grains",
      "price": 210.00,
      "currency": "INR",
      "quantity": 1,
      "unit": "kg",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 5,
      "product_name": "Tata Sampann Toor Dal",
      "category": "Pulses",
      "price": 165.00,
      "currency": "INR",
      "quantity": 1,
      "unit": "kg",
      "in_stock": false,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 6,
      "product_name": "Maggi 2-Minute Noodles",
      "category": "Snacks",
      "price": 58.00,
      "currency": "INR",
      "quantity": 280,
      "unit": "g",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 7,
      "product_name": "Fortune Sunlite Refined Sunflower Oil",
      "category": "Oils",
      "price": 145.00,
      "currency": "INR",
      "quantity": 1,
      "unit": "liter",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 8,
      "product_name": "Amul Taaza Toned Milk",
      "category": "Dairy",
      "price": 72.00,
      "currency": "INR",
      "quantity": 1,
      "unit": "liter",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 9,
      "product_name": "Brooke Bond Red Label Tea",
      "category": "Beverages",
      "price": 240.00,
      "currency": "INR",
      "quantity": 500,
      "unit": "g",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
    {
      "id": 10,
      "product_name": "Haldiram's Aloo Bhujia",
      "category": "Snacks",
      "price": 55.00,
      "currency": "INR",
      "quantity": 200,
      "unit": "g",
      "in_stock": true,
      "image_url": "https://img.freepik.com/free-vector/vector-ripe-yellow-banana-bunch-isolated-white-background_1284-45456.jpg",
    },
  ];
}
